/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4f882060df4cd802d3ee7bf6cdd0f10f)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
	DB: D1Database;
	NODE_ENV: string;
	FIREBASE_PROJECT_ID: string;
	REPLICATE_API_TOKEN: string;
	RESEND_API_KEY: string;
	RESEND_FROM_EMAIL: string;
	NEXT_PUBLIC_APP_URL: string;
	XENDIT_SECRET_KEY: string;
	XENDIT_WEBHOOK_TOKEN: string;
	SKIP_LOGIN_OTP: string;
	REALTIME_HUB: DurableObjectNamespace<import("./worker").RealtimeHubDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "RealtimeHubDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "FIREBASE_PROJECT_ID" | "REPLICATE_API_TOKEN" | "RESEND_API_KEY" | "RESEND_FROM_EMAIL" | "NEXT_PUBLIC_APP_URL" | "XENDIT_SECRET_KEY" | "XENDIT_WEBHOOK_TOKEN" | "SKIP_LOGIN_OTP">> {}
}
