/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fa7c79268ac4a64d995dc91baab205f8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env {
		NODE_ENV: string;
		NEXT_PUBLIC_SUPABASE_URL: string;
		NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
		SUPABASE_SERVICE_ROLE_KEY: string;
		REPLICATE_API_TOKEN: string;
		RESEND_API_KEY: string;
		RESEND_FROM_EMAIL: string;
		NEXT_PUBLIC_APP_URL: string;
		XENDIT_SECRET_KEY: string;
		XENDIT_WEBHOOK_TOKEN: string;
		SKIP_LOGIN_OTP: string;
	}
}
interface Env extends Cloudflare.Env {}
