/* eslint-disable */
/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fa7c79268ac4a64d995dc91baab205f8)
// Ditambah manual: SUPABASE_JWT_SECRET, DB, ASSETS (jalankan `npm run types:cf` lalu merge ulang jika perlu).
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker')
  }
  interface Env {
    NODE_ENV: string
    NEXT_PUBLIC_SUPABASE_URL: string
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string
    SUPABASE_SERVICE_ROLE_KEY: string
    /** Legacy JWT secret (HS256). Token ECC pakai JWKS — secret opsional jika semua token ES256. */
    SUPABASE_JWT_SECRET?: string
    /** Juga dipakai Try On via model `google/gemini-2.5-*` di Replicate. */
    REPLICATE_API_TOKEN: string
    RESEND_API_KEY: string
    RESEND_FROM_EMAIL: string
    NEXT_PUBLIC_APP_URL: string
    XENDIT_SECRET_KEY: string
    XENDIT_WEBHOOK_TOKEN: string
    SKIP_LOGIN_OTP: string
    SKIP_OTP?: string
    DB?: D1Database
    ASSETS?: R2Bucket
  }
}
interface Env extends Cloudflare.Env {}
